import type { CSSProperties } from 'react'

export const editableRootStyle = {
  // Luxury editorial system: warm ivory paper, deep indigo ink, teal + mint
  // accents. Generous radius, soft indigo-tinted shadows, serif display type.
  '--slot4-page-bg': '#fbf8f1',
  '--slot4-page-text': '#22224a',
  '--slot4-panel-bg': '#f2efe2',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#5b5c7c',
  '--slot4-soft-muted-text': '#8c8dae',
  '--slot4-accent': '#31326f',
  '--slot4-accent-fill': '#31326f',
  '--slot4-accent-soft': '#a8fbd3',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#1c1d42',
  '--slot4-dark-text': '#f3eedd',
  '--slot4-media-bg': '#e9eaf4',
  '--slot4-cream': '#fbf8f1',
  '--slot4-warm': '#f2efe2',
  '--slot4-lavender': '#eaf0fa',
  '--slot4-gray': '#f4f3ee',
  '--slot4-body-gradient': 'none',
  '--slot4-ink': '#1c1d42',
  '--slot4-ink-soft': '#26275a',
  '--slot4-ink-text': '#f3eedd',
  '--slot4-ink-muted': '#b9bee0',
  '--slot4-teal': '#4fb7b3',
  '--slot4-mint': '#a8fbd3',
  '--slot4-violet': '#637ab9',
  '--editable-page-bg': '#fbf8f1',
  '--editable-page-text': '#22224a',
  '--editable-container': '1320px',
  '--editable-border': '#e3e1ef',
  '--editable-nav-bg': '#fffdf8',
  '--editable-nav-text': '#22224a',
  '--editable-nav-active': '#31326f',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#31326f',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#1c1d42',
  '--editable-footer-text': '#f3eedd',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  inkBg: 'bg-[var(--slot4-ink)]',
  inkText: 'text-[var(--slot4-ink-text)]',
  inkMutedText: 'text-[var(--slot4-ink-muted)]',
  tealText: 'text-[var(--slot4-teal)]',
  tealBg: 'bg-[var(--slot4-teal)]',
  mintBg: 'bg-[var(--slot4-mint)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_1px_3px_rgba(35,35,90,0.08)]',
  shadowStrong: 'shadow-[0_20px_50px_rgba(23,24,58,0.18)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(20,21,48,0.02),rgba(20,21,48,0.82))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[150px] shrink-0 snap-start sm:w-[170px]',
  },
  type: {
    eyebrow: 'text-xs font-semibold uppercase tracking-[0.32em] text-[var(--slot4-accent)]',
    heroTitle: 'editable-display text-4xl font-medium leading-[1.06] tracking-[-0.01em] sm:text-5xl lg:text-[3.75rem]',
    sectionTitle: 'editable-display text-3xl font-medium tracking-[-0.01em] sm:text-4xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-[1.5rem] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[1.5rem] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[1.5rem] ${editablePalette.inkBg} ${editablePalette.inkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-7 py-3.5 text-sm font-semibold tracking-[0.01em] text-[var(--slot4-on-accent)] transition duration-300 hover:bg-[var(--slot4-teal)] hover:-translate-y-0.5 active:translate-y-0`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-7 py-3.5 text-sm font-semibold tracking-[0.01em] text-[var(--slot4-page-text)] transition duration-300 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] hover:-translate-y-0.5`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-teal)] px-7 py-3.5 text-sm font-semibold text-[var(--slot4-ink)] transition duration-300 hover:brightness-105 hover:-translate-y-0.5`,
  },
  media: {
    frame: `relative overflow-hidden rounded-[1.25rem] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-500 hover:-translate-y-1.5 hover:shadow-[0_28px_70px_rgba(31,32,90,0.16)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
